services:
  traefik:
    image: traefik:v3.0.3
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=me@myemail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-letsencrypt:/letsencrypt"
    networks:
      - traefik

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - "./html:/usr/share/nginx/html" # Serve your index.html from the ./html folder
    labels:
      - "traefik.http.routers.web.rule=Host(`example.com`)" # Replace with your domain or IP
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - traefik

volumes:
  traefik-letsencrypt:

networks:
  traefik:
    external: true